#!/bin/bash
# Not a real compose file, but a script to compose the (currently just one) image. 
podman run -d --name freva-gpt-2-backend-instance -p 8502:8502 -v /work/bm1159/XCES/data4xces:/work/bm1159/XCES/data4xces:ro -v ./logs:/app/logs -v ./threads:/app/threads -v ./target:/app/target -v ./testdata:/data/inputFiles -v /work/bm1159/XCES/xces-work/k204225/MYWORK:/work/bm1159/XCES/xces-work/k204225/MYWORK:ro freva-gpt2-backend 
#          ^    	    ^				^           ^                                                     ^      ^                   ^                         ^                       ^                             ^                                                                                        ^     
# Runs the Image            | 				|           |                                                     |      |                   |                         |                       |                             |                                                                                        |       
#          |                | 				|           |                                                     |      |                   |                         |                       |                             |                                                                                        |       
#          ^ In detached mode to not close when the terminal window closes                                                |      |                   |                         |                       |                             |                                                                                        |                    
#                           | 				|           |                                                     |      |                   |                         |                       |                             |                                                                                        |              
#                           ^ Call the resulting container "freva-gpt-2-backend-instance"                                 |      |                   |                         |                       |                             |                                                                                        |                   
#							|           |                                                     |      |                   |                         |                       |                             |                                                                                        |                   
#							^ Binding the port at internally 8502 to externally 8502          |      |                   |                         |                       |                             |                                                                                        |                   
#                                                                   |                                                     |      |                   |                         |                       |                             |                                                                                        |                   
#								    ^ Giving access to the data4xces directory, read-only ^ mapping internally to the same directory           |                       |                             |                                                                                        |
#                                                                                                                                |                   |                         |                       |                             |                                                                                        |
#                                                                                                                                ^ Logs are written to ./logs, even from inside; you don't have to enter the container to read them  |                                                                                        |
#                                                                                                                                                    |                         |                       |                             |                                                                                        |
#                                                                                                                                                    ^ Same with threads       |                       |                             |                                                                                        |
#                                                                                                                                                                              |                       |                             |                                                                                        |
#                                                                                                                                                                              ^ Caches compilation between container starts         |                                                                                        |
#                                                                                                                                                                                                      |                             |                                                                                        |
#                                                                                                                                                                                                      ^ Access to test datasets     |                                                                                        |
#                                                                                                                                                                                                                                    |                                                                                        |
#                                                                                                                                                                                                                                    ^ Access to further XCES data                                                            |
#                                                                                                                                                                                                                                                                                                                             |
#                                                                                                                                                                                                                                                                                                                             ^ Name of Image